#!/usr/bin/env python3
"""
道 · 参数化代码生成器 — Parametric Codegen v1.0
=================================================
反者道之动 — 从DesignTree逆向生成可执行的参数化建模代码。

旧架构: LLM → ops JSON → freecad_backend → output
                ↑ 此处是天花板：只有原语，没有设计语言

新架构: LLM → DesignTree → [本模块] → CadQuery Python代码 → 执行 → output
                                        ↑ 完整的参数化建模语言

本模块是"几何编译器"的核心 — 将结构化的设计意图编译为可执行的Python代码。
生成的代码使用 CadQuery (首选) 或 FreeCAD PartDesign API。

唯变所适: 代码是可修改的文本，LLM可以理解、调试、迭代。
          这比JSON ops序列灵活无数倍。

Usage:
    from parametric_codegen import ParametricCodegen
    from design_intent_compiler import DesignIntentCompiler

    compiler = DesignIntentCompiler()
    tree, report, plan = compiler.compile_and_plan(spec)

    codegen = ParametricCodegen()
    code = codegen.generate(tree, plan)  # → Python source code string
    result = codegen.execute(code, output_dir="./output")
"""

import json
import math
import textwrap
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Tuple
from pathlib import Path

from design_intent_compiler import (
    DesignTree, PartNode, FeatureNode, BuildPlan, BuildStep,
    FeatureType, Function, JoinMethod, Process,
    METRIC_SCREWS, PROCESS_LIMITS,
)

__version__ = "1.0.0"
__all__ = ["ParametricCodegen", "CodeResult"]


# ═══════════════════════════════════════════════════════════════════════════
# 一、CadQuery 代码模板库 — 每个模板都是经过验证的、可靠的构建模式
# ═══════════════════════════════════════════════════════════════════════════

# 文件头模板
CQ_HEADER = '''#!/usr/bin/env python3
"""
{description}
Generated by 道·参数化代码生成器 v1.0
Design: {name}
Engine: CadQuery
"""
import cadquery as cq
from cadquery import exporters
import math
import os

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

# ═══ Parameters ═══════════════════════════════════════════════════════════
{params_block}
'''

# 零件代码模板
CQ_PART_TEMPLATE = '''
# ─── Part: {name} ({function}) ────────────────────────────────────────────
{code}
'''

# 导出模板
CQ_EXPORT = '''
# ═══ Export ═══════════════════════════════════════════════════════════════
{export_code}
print("Build complete: {name}")
'''

# 装配模板
CQ_ASSEMBLY = '''
# ═══ Assembly ════════════════════════════════════════════════════════════
assy = cq.Assembly()
{assembly_code}
'''


# ═══════════════════════════════════════════════════════════════════════════
# 二、特征→CadQuery代码 的编译规则
# ═══════════════════════════════════════════════════════════════════════════

def _gen_body_box(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    d = part.dims
    L = p.get("L", d.get("L", 20))
    W = p.get("W", d.get("W", 15))
    H = p.get("H", d.get("H", 10))
    centered = p.get("centered", True)
    if centered:
        return f'{var} = cq.Workplane("XY").box({L}, {W}, {H})'
    else:
        return f'{var} = cq.Workplane("XY").rect({L}, {W}).extrude({H})'


def _gen_body_cylinder(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    d = part.dims
    R = p.get("R", d.get("R", 10))
    H = p.get("H", d.get("H", 20))
    return f'{var} = cq.Workplane("XY").circle({R}).extrude({H})'


def _gen_body_sphere(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    R = p.get("R", part.dims.get("R", 10))
    return f'{var} = cq.Workplane("XY").sphere({R})'


def _gen_body_cone(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    R1 = p.get("R1", 15)
    R2 = p.get("R2", 5)
    H = p.get("H", 20)
    # CadQuery: loft between two circles
    return (
        f'{var} = (\n'
        f'    cq.Workplane("XY")\n'
        f'    .circle({R1})\n'
        f'    .workplane(offset={H})\n'
        f'    .circle({R2})\n'
        f'    .loft()\n'
        f')'
    )


def _gen_body_torus(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    R1 = p.get("R1", 15)  # major radius
    R2 = p.get("R2", 5)   # minor radius
    return f'{var} = cq.Workplane("XZ").circle({R2}).revolve(360, ({R1}, 0), (0, 1))'


def _gen_body_prism(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    n = p.get("n", 6)
    R = p.get("R", 10)
    H = p.get("H", 20)
    return f'{var} = cq.Workplane("XY").polygon({n}, {R*2}).extrude({H})'


def _gen_pad(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    H = p.get("height", p.get("H", 10))
    sketch = feat.sketch

    if sketch and sketch.get("type") == "rect":
        w, h = sketch.get("W", 20), sketch.get("H", 10)
        return f'{var} = {var}.faces(">Z").workplane().rect({w}, {h}).extrude({H})'
    elif sketch and sketch.get("type") == "circle":
        r = sketch.get("R", 5)
        return f'{var} = {var}.faces(">Z").workplane().circle({r}).extrude({H})'
    elif sketch and sketch.get("type") == "polygon":
        pts = sketch.get("points", [])
        pts_str = ", ".join(f"({x}, {y})" for x, y in pts)
        return (
            f'{var} = (\n'
            f'    {var}.faces(">Z").workplane()\n'
            f'    .polyline([{pts_str}]).close()\n'
            f'    .extrude({H})\n'
            f')'
        )
    else:
        sketch_desc = p.get("sketch_desc", "profile")
        return f'# TODO: Define sketch for pad ({sketch_desc})\n{var} = {var}.faces(">Z").workplane().rect(10, 10).extrude({H})'


def _gen_pocket(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    depth = p.get("depth", 5)
    width = p.get("width", p.get("W", 10))
    height = p.get("height", p.get("H", 10))
    face = p.get("face", ">Z")

    if p.get("shape") == "circle":
        r = p.get("R", width / 2)
        return f'{var} = {var}.faces("{face}").workplane().hole({r*2}, depth={depth})'
    else:
        return f'{var} = {var}.faces("{face}").workplane().rect({width}, {height}).cutBlind(-{depth})'


def _gen_hole(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    d = p.get("diameter", p.get("d", 3.4))
    depth = p.get("depth", "thru")
    face = p.get("face", ">Z")
    pos = p.get("position")

    # 智能面选择: 如果零件有shell且shell移除了目标面，切换到对面
    shell_feats = [f for f in part.features if f.type == FeatureType.SHELL]
    if shell_feats and face == ">Z":
        shell_face = shell_feats[0].params.get("faces_to_remove", ">Z")
        if shell_face == ">Z" and feat.order > shell_feats[0].order:
            face = "<Z"  # shell已移除顶面，改用底面

    lines = []
    wp = f'{var}.faces("{face}").workplane()'
    if pos:
        wp = f'{wp}.center({pos[0]}, {pos[1]})'

    if depth == "thru":
        lines.append(f'{var} = {wp}.hole({d})')
    else:
        lines.append(f'{var} = {wp}.hole({d}, depth={depth})')

    # 沉头孔
    if p.get("countersink"):
        cs_d = p.get("countersink_d", d * 2)
        cs_angle = p.get("countersink_angle", 82)
        lines[-1] = f'{var} = {wp}.cskHole({d}, {cs_d}, {cs_angle})'
    elif p.get("counterbore"):
        cb_d = p.get("counterbore_d", d * 1.8)
        cb_depth = p.get("counterbore_depth", d * 0.5)
        lines[-1] = f'{var} = {wp}.cboreHole({d}, {cb_d}, {cb_depth})'

    return "\n".join(lines)


def _gen_fillet(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    r = p.get("radius", 2)
    edges = p.get("edges", "all")

    if edges == "all":
        return f'{var} = {var}.edges().fillet({r})'
    elif edges == "vertical":
        return f'{var} = {var}.edges("|Z").fillet({r})'
    elif edges == "top":
        return f'{var} = {var}.edges(">Z").fillet({r})'
    elif edges == "bottom":
        return f'{var} = {var}.edges("<Z").fillet({r})'
    else:
        return f'{var} = {var}.edges().fillet({r})  # edges selector: {edges}'


def _gen_chamfer(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    s = p.get("size", 1)
    edges = p.get("edges", "all")

    if edges == "all":
        return f'{var} = {var}.edges().chamfer({s})'
    elif edges == "vertical":
        return f'{var} = {var}.edges("|Z").chamfer({s})'
    else:
        return f'{var} = {var}.edges().chamfer({s})'


def _gen_shell(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    t = p.get("thickness", 2)
    face = p.get("faces_to_remove", ">Z")
    return (
        f'# Shell: remove face {face}, wall={t}mm\n'
        f'{var} = {var}.faces("{face}").shell(-{t})'
    )


def _gen_pattern_linear(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    count = p.get("count", 3)
    spacing = p.get("spacing", 10)
    dx = p.get("dx", spacing)
    dy = p.get("dy", 0)

    # 如果包含孔的位置列表
    positions = p.get("positions")
    hole_d = p.get("hole_d", 3.4)

    if positions:
        lines = []
        for i, pos in enumerate(positions):
            lines.append(f'{var} = {var}.faces(">Z").workplane().center({pos[0]}, {pos[1]}).hole({hole_d})')
            if i < len(positions) - 1:
                lines.append(f'  # hole at ({pos[0]}, {pos[1]})')
        return "\n".join(lines)
    else:
        return (
            f'# Linear pattern: {count}x, spacing ({dx}, {dy})\n'
            f'for _i in range({count}):\n'
            f'    {var} = {var}.faces(">Z").workplane().center({dx}*_i, {dy}*_i).hole({hole_d})'
        )


def _gen_pattern_polar(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    count = p.get("count", 6)
    hole_d = p.get("hole_d", 6.6)
    pcd = p.get("pcd", 45)

    return (
        f'# Polar pattern: {count}x holes on PCD={pcd}mm\n'
        f'_angles = [i * 360 / {count} for i in range({count})]\n'
        f'for _a in _angles:\n'
        f'    _x = {pcd/2} * math.cos(math.radians(_a))\n'
        f'    _y = {pcd/2} * math.sin(math.radians(_a))\n'
        f'    {var} = {var}.faces(">Z").workplane().center(_x, _y).hole({hole_d})'
    )


def _gen_mirror(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    plane = p.get("plane", "YZ")
    return f'{var} = {var}.mirror("{plane}")'


def _gen_revolve(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    angle = p.get("angle", 360)
    axis_start = p.get("axis_start", "(0, 0)")
    axis_end = p.get("axis_end", "(0, 1)")
    return f'{var} = {var}.revolve({angle}, {axis_start}, {axis_end})'


def _gen_sweep(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    path_pts = p.get("path_points", [[0,0,0], [0,0,20]])
    R = p.get("R", 3)

    pts_str = ", ".join(f"({x}, {y}, {z})" for x, y, z in path_pts)
    return (
        f'_path = cq.Workplane("XZ").spline([{pts_str}])\n'
        f'{var} = (\n'
        f'    cq.Workplane("XY")\n'
        f'    .circle({R})\n'
        f'    .sweep(_path)\n'
        f')'
    )


def _gen_loft(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    profiles = p.get("profiles", [])
    # Generate loft placeholder
    return (
        f'# Loft between profiles\n'
        f'{var} = (\n'
        f'    cq.Workplane("XY")\n'
        f'    .rect(20, 20)\n'
        f'    .workplane(offset=20)\n'
        f'    .circle(10)\n'
        f'    .loft()\n'
        f')'
    )


def _gen_boss(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    d = p.get("diameter", 8)
    h = p.get("height", 5)
    pos = p.get("position")
    face = p.get("face", ">Z")

    if pos:
        return f'{var} = {var}.faces("{face}").workplane().center({pos[0]}, {pos[1]}).circle({d/2}).extrude({h})'
    else:
        return f'{var} = {var}.faces("{face}").workplane().circle({d/2}).extrude({h})'


def _gen_groove(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    w = p.get("width", 3)
    depth = p.get("depth", 2)
    length = p.get("length", 20)
    face = p.get("face", ">Z")

    return f'{var} = {var}.faces("{face}").workplane().slot2D({length}, {w}).cutBlind(-{depth})'


def _gen_rib(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    t = p.get("thickness", 2)
    h = p.get("height", 10)
    length = p.get("length", 20)
    return (
        f'# Rib: t={t}, h={h}, L={length}\n'
        f'{var} = {var}.faces(">Z").workplane().rect({t}, {length}).extrude({h})'
    )


def _gen_thread(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    d = p.get("diameter", 8)
    pitch = p.get("pitch", 1.25)
    length = p.get("length", 20)
    return (
        f'# Thread: M{d}x{pitch}, L={length}\n'
        f'# Note: True threads are heavy geometry — using simplified representation\n'
        f'{var} = cq.Workplane("XY").circle({d/2}).extrude({length})'
    )


def _gen_import_stl(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    path = p.get("path", "model.stl")
    return f'{var} = cq.importers.importStep("{path}")  # or use trimesh for STL'


def _gen_import_step(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    path = p.get("path", "model.step")
    return f'{var} = cq.importers.importStep("{path}")'


def _gen_custom_sketch(feat: FeatureNode, part: PartNode, var: str) -> str:
    p = feat.params
    sketch = feat.sketch
    H = p.get("height", p.get("H", 10))

    if not sketch:
        return f'# Custom sketch: define points\n{var} = cq.Workplane("XY").rect(20, 10).extrude({H})'

    sketch_type = sketch.get("type", "polyline")
    if sketch_type == "polyline":
        pts = sketch.get("points", [(0,0), (20,0), (20,10), (0,10)])
        pts_str = ", ".join(f"({x}, {y})" for x, y in pts)
        return (
            f'{var} = (\n'
            f'    cq.Workplane("XY")\n'
            f'    .polyline([{pts_str}]).close()\n'
            f'    .extrude({H})\n'
            f')'
        )
    elif sketch_type == "circle":
        r = sketch.get("R", 10)
        return f'{var} = cq.Workplane("XY").circle({r}).extrude({H})'
    else:
        return f'# Custom sketch type: {sketch_type}\n{var} = cq.Workplane("XY").rect(20, 10).extrude({H})'


# 特征类型 → 代码生成函数的映射
FEATURE_GENERATORS = {
    FeatureType.BODY_BOX:       _gen_body_box,
    FeatureType.BODY_CYLINDER:  _gen_body_cylinder,
    FeatureType.BODY_SPHERE:    _gen_body_sphere,
    FeatureType.BODY_CONE:      _gen_body_cone,
    FeatureType.BODY_TORUS:     _gen_body_torus,
    FeatureType.BODY_PRISM:     _gen_body_prism,
    FeatureType.PAD:            _gen_pad,
    FeatureType.POCKET:         _gen_pocket,
    FeatureType.HOLE:           _gen_hole,
    FeatureType.FILLET:         _gen_fillet,
    FeatureType.CHAMFER:        _gen_chamfer,
    FeatureType.SHELL:          _gen_shell,
    FeatureType.PATTERN_LINEAR: _gen_pattern_linear,
    FeatureType.PATTERN_POLAR:  _gen_pattern_polar,
    FeatureType.MIRROR:         _gen_mirror,
    FeatureType.REVOLVE:        _gen_revolve,
    FeatureType.SWEEP:          _gen_sweep,
    FeatureType.LOFT:           _gen_loft,
    FeatureType.BOSS:           _gen_boss,
    FeatureType.GROOVE:         _gen_groove,
    FeatureType.RIB:            _gen_rib,
    FeatureType.THREAD:         _gen_thread,
    FeatureType.IMPORT_STL:     _gen_import_stl,
    FeatureType.IMPORT_STEP:    _gen_import_step,
    FeatureType.CUSTOM_SKETCH:  _gen_custom_sketch,
}


# ═══════════════════════════════════════════════════════════════════════════
# 三、代码生成器核心
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class CodeResult:
    """代码生成结果"""
    code: str
    engine: str
    parts: List[str]
    output_files: Dict[str, str] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)


class ParametricCodegen:
    """
    参数化代码生成器 — 将DesignTree编译为可执行的Python代码。

    道法自然: 生成的代码是自然的、可读的、可修改的。
    唯变所适: 代码可以被LLM理解和迭代修改。
    """

    def __init__(self, engine: str = "cadquery"):
        self.engine = engine

    def generate(self, tree: DesignTree, plan: Optional[BuildPlan] = None,
                 output_dir: str = "./output") -> CodeResult:
        """
        从DesignTree生成完整的参数化建模代码。

        Args:
            tree: 设计树
            plan: 构建计划 (可选，用于确定引擎)
            output_dir: 输出目录路径

        Returns:
            CodeResult 包含生成的代码
        """
        engine = plan.engine if plan else self.engine

        if engine == "cadquery":
            return self._gen_cadquery(tree, output_dir)
        elif engine == "freecad":
            return self._gen_freecad(tree, output_dir)
        else:
            return self._gen_cadquery(tree, output_dir)

    def _gen_cadquery(self, tree: DesignTree, output_dir: str) -> CodeResult:
        """生成 CadQuery 代码"""
        warnings = []
        sections = []

        # 1. 参数块
        params_lines = []
        for k, v in tree.global_params.items():
            if isinstance(v, str):
                params_lines.append(f'{k} = "{v}"')
            else:
                params_lines.append(f'{k} = {v}')

        for part in tree.parts:
            params_lines.append(f'# {part.name} dims')
            for k, v in part.dims.items():
                params_lines.append(f'{part.name}_{k} = {v}')

        params_block = "\n".join(params_lines) if params_lines else "# No global parameters"

        header = CQ_HEADER.format(
            description=tree.description or tree.name,
            name=tree.name,
            params_block=params_block,
        )
        sections.append(header)

        # 2. 零件代码
        part_vars = {}
        for part in tree.parts:
            code_lines = []
            var = f'part_{part.name}'
            part_vars[part.name] = var

            # 按 order 排序特征
            sorted_features = sorted(part.features, key=lambda f: f.order)

            is_first = True
            for feat in sorted_features:
                gen_fn = FEATURE_GENERATORS.get(feat.type)
                if gen_fn is None:
                    warnings.append(f"No generator for feature type: {feat.type.value}")
                    code_lines.append(f'# UNSUPPORTED: {feat.type.value} — {json.dumps(feat.params, ensure_ascii=False)}')
                    continue

                if is_first and feat.type.value.startswith("body_"):
                    # 基体特征 — 创建新变量
                    code_lines.append(gen_fn(feat, part, var))
                    is_first = False
                elif is_first:
                    # 第一个特征不是基体 → 先创建默认基体
                    d = part.dims
                    if d.get("L") and d.get("W") and d.get("H"):
                        code_lines.append(f'{var} = cq.Workplane("XY").box({d["L"]}, {d["W"]}, {d["H"]})')
                    elif d.get("R") and d.get("H"):
                        code_lines.append(f'{var} = cq.Workplane("XY").circle({d["R"]}).extrude({d["H"]})')
                    else:
                        code_lines.append(f'{var} = cq.Workplane("XY").box(20, 15, 10)  # default body')
                    is_first = False
                    code_lines.append(gen_fn(feat, part, var))
                else:
                    # 后续特征 — 追加到现有变量
                    code_lines.append(gen_fn(feat, part, var))

            # 如果零件没有特征但有dims，自动创建基体
            if not part.features:
                d = part.dims
                if d.get("L") and d.get("W") and d.get("H"):
                    code_lines.append(f'{var} = cq.Workplane("XY").box({d["L"]}, {d["W"]}, {d["H"]})')
                elif d.get("R") and d.get("H"):
                    code_lines.append(f'{var} = cq.Workplane("XY").circle({d["R"]}).extrude({d["H"]})')
                else:
                    code_lines.append(f'{var} = cq.Workplane("XY").box(20, 15, 10)  # placeholder')
                    warnings.append(f"Part '{part.name}' has no features or dims — using placeholder")

            section = CQ_PART_TEMPLATE.format(
                name=part.name,
                function=part.function.value,
                code="\n".join(code_lines),
            )
            sections.append(section)

        # 3. 装配 / 连接
        if tree.joins:
            assy_lines = []
            for join in tree.joins:
                va = part_vars.get(join.part_a, f'part_{join.part_a}')
                vb = part_vars.get(join.part_b, f'part_{join.part_b}')

                if join.method == JoinMethod.FUSE:
                    pos = join.params.get("position")
                    if pos:
                        assy_lines.append(
                            f'# Fuse {join.part_a} + {join.part_b}\n'
                            f'{vb}_placed = {vb}.translate(({pos[0]}, {pos[1]}, {pos[2]}))\n'
                            f'result = {va}.union({vb}_placed)'
                        )
                    else:
                        assy_lines.append(f'result = {va}.union({vb})')
                elif join.method == JoinMethod.NONE:
                    pass
                else:
                    assy_lines.append(
                        f'assy.add({va}, name="{join.part_a}")\n'
                        f'assy.add({vb}, name="{join.part_b}")'
                    )

            if assy_lines:
                has_fuse = any(j.method == JoinMethod.FUSE for j in tree.joins)
                has_assy = any(j.method not in (JoinMethod.FUSE, JoinMethod.NONE) for j in tree.joins)
                preamble = ""
                if has_assy:
                    preamble = "assy = cq.Assembly()\n"
                sections.append("\n# ═══ Assembly / Joins ═══\n" + preamble + "\n\n".join(assy_lines))
                # Set result from fuse chain or first part
                if not has_fuse:
                    first_var = list(part_vars.values())[0]
                    sections.append(f'\nresult = {first_var}  # individual parts in assy')

        # 如果没有连接 或 连接中没有fuse产生result，设置result = 第一个零件
        has_result = any('result =' in s for s in sections)
        if not has_result and part_vars:
            first_var = list(part_vars.values())[0]
            sections.append(f'\nresult = {first_var}')

        # 4. 导出
        export_lines = []
        out = output_dir.replace("\\", "/")
        name = tree.name
        output_files = {}

        export_lines.append(f'os.makedirs(r"{out}", exist_ok=True)')

        for fmt in ["stl", "step"]:
            fpath = f'{out}/{name}.{fmt}'
            output_files[fmt] = fpath
            if fmt == "stl":
                export_lines.append(f'exporters.export(result, r"{fpath}")')
            elif fmt == "step":
                export_lines.append(f'exporters.export(result, r"{fpath}", exportType="STEP")')

        export_section = CQ_EXPORT.format(
            export_code="\n".join(export_lines),
            name=name,
        )
        sections.append(export_section)

        code = "\n".join(sections)

        return CodeResult(
            code=code,
            engine="cadquery",
            parts=list(part_vars.keys()),
            output_files=output_files,
            warnings=warnings,
        )

    def _gen_freecad(self, tree: DesignTree, output_dir: str) -> CodeResult:
        """生成 FreeCAD PartDesign 代码"""
        warnings = []
        lines = [
            '#!/usr/bin/env python3',
            '"""',
            f'{tree.description or tree.name}',
            'Generated by 道·参数化代码生成器 v1.0 (FreeCAD PartDesign)',
            '"""',
            'import FreeCAD as App',
            'import Part',
            'from FreeCAD import Base',
            'import os',
            '',
            f'OUTPUT_DIR = r"{output_dir}"',
            'os.makedirs(OUTPUT_DIR, exist_ok=True)',
            '',
            f'doc = App.newDocument("{tree.name}")',
            '',
        ]

        part_vars = {}
        for part in tree.parts:
            var = f'obj_{part.name}'
            part_vars[part.name] = var

            lines.append(f'# ─── Part: {part.name} ───')
            d = part.dims
            if d.get("L") and d.get("W") and d.get("H"):
                lines.append(f'{var} = doc.addObject("Part::Feature", "{part.name}")')
                lines.append(f'{var}.Shape = Part.makeBox({d["L"]}, {d["W"]}, {d["H"]})')
            elif d.get("R") and d.get("H"):
                lines.append(f'{var} = doc.addObject("Part::Feature", "{part.name}")')
                lines.append(f'{var}.Shape = Part.makeCylinder({d["R"]}, {d["H"]})')
            else:
                lines.append(f'{var} = doc.addObject("Part::Feature", "{part.name}")')
                lines.append(f'{var}.Shape = Part.makeBox(20, 15, 10)')

            # Apply features
            for feat in sorted(part.features, key=lambda f: f.order):
                if feat.type == FeatureType.FILLET:
                    r = feat.params.get("radius", 2)
                    lines.append(f'try:')
                    lines.append(f'    {var}.Shape = {var}.Shape.makeFillet({r}, {var}.Shape.Edges)')
                    lines.append(f'except: pass  # fillet may fail on some edges')
                elif feat.type == FeatureType.SHELL:
                    t = feat.params.get("thickness", 2)
                    lines.append(f'try:')
                    lines.append(f'    _faces = [{var}.Shape.Faces[0]]  # top face')
                    lines.append(f'    {var}.Shape = {var}.Shape.makeThickness(_faces, -{t}, 0.001)')
                    lines.append(f'except: pass')

            lines.append('')

        # Export
        lines.append('doc.recompute()')
        name = tree.name
        output_files = {}

        stl_path = f'{output_dir}/{name}.stl'.replace("\\", "/")
        step_path = f'{output_dir}/{name}.step'.replace("\\", "/")
        fcstd_path = f'{output_dir}/{name}.FCStd'.replace("\\", "/")

        output_files["stl"] = stl_path
        output_files["step"] = step_path
        output_files["fcstd"] = fcstd_path

        lines.append(f'# Export')
        lines.append(f'import Mesh')

        first_var = list(part_vars.values())[0] if part_vars else "None"
        lines.append(f'if {first_var} and hasattr({first_var}, "Shape"):')
        lines.append(f'    Mesh.export([{first_var}], r"{stl_path}")')
        lines.append(f'    Part.export([{first_var}.Shape], r"{step_path}")')
        lines.append(f'doc.saveAs(r"{fcstd_path}")')
        lines.append(f'print("Build complete: {name}")')

        code = "\n".join(lines)
        return CodeResult(
            code=code, engine="freecad",
            parts=list(part_vars.keys()),
            output_files=output_files,
            warnings=warnings,
        )

    def execute(self, code_result: CodeResult, output_dir: Optional[str] = None) -> Dict:
        """
        执行生成的代码并返回结果。

        这是与 DaoEngine 的桥接点 — 实际执行委托给 DaoEngine。
        """
        # 保存代码到文件
        if output_dir:
            out = Path(output_dir)
        else:
            out = Path(code_result.output_files.get("stl", "./output")).parent

        out.mkdir(parents=True, exist_ok=True)
        script_path = out / f"{code_result.engine}_build.py"
        script_path.write_text(code_result.code, encoding="utf-8")

        return {
            "ok": True,
            "script_path": str(script_path),
            "engine": code_result.engine,
            "parts": code_result.parts,
            "output_files": code_result.output_files,
            "warnings": code_result.warnings,
            "note": "Code saved. Execute with DaoEngine or directly with CadQuery/FreeCAD.",
        }


# ═══════════════════════════════════════════════════════════════════════════
# 四、CLI
# ═══════════════════════════════════════════════════════════════════════════

def _demo():
    """演示: 从规格生成CadQuery代码"""
    from design_intent_compiler import DesignIntentCompiler

    spec = {
        "name": "electronics_enclosure",
        "description": "PCB电子外壳，带散热孔和螺丝安装柱",
        "process": "fdm",
        "global_params": {
            "pcb_l": 60, "pcb_w": 40, "pcb_h": 1.6,
            "clearance": 1.0,
        },
        "parts": [
            {
                "name": "body",
                "function": "contain",
                "dims": {"L": 66, "W": 46, "H": 25, "wall": 2},
                "features": [
                    {"name": "box", "type": "body_box", "params": {"L": 66, "W": 46, "H": 25}},
                    {"name": "shell", "type": "shell", "params": {"thickness": 2, "faces_to_remove": ">Z"}},
                    {"name": "fillet_ext", "type": "fillet", "params": {"radius": 3, "edges": "vertical"}},
                    {"name": "mount1", "type": "boss", "params": {"diameter": 7, "height": 5, "position": [-25, -15]}},
                    {"name": "mount2", "type": "boss", "params": {"diameter": 7, "height": 5, "position": [25, -15]}},
                    {"name": "mount3", "type": "boss", "params": {"diameter": 7, "height": 5, "position": [-25, 15]}},
                    {"name": "mount4", "type": "boss", "params": {"diameter": 7, "height": 5, "position": [25, 15]}},
                    {"name": "screw1", "type": "hole", "params": {"d": 2.7, "depth": 5, "face": ">Z", "position": [-25, -15]}},
                    {"name": "screw2", "type": "hole", "params": {"d": 2.7, "depth": 5, "face": ">Z", "position": [25, -15]}},
                    {"name": "screw3", "type": "hole", "params": {"d": 2.7, "depth": 5, "face": ">Z", "position": [-25, 15]}},
                    {"name": "screw4", "type": "hole", "params": {"d": 2.7, "depth": 5, "face": ">Z", "position": [25, 15]}},
                ],
            },
            {
                "name": "lid",
                "function": "shield",
                "dims": {"L": 66, "W": 46, "H": 4},
                "features": [
                    {"name": "plate", "type": "body_box", "params": {"L": 66, "W": 46, "H": 4}},
                    {"name": "lip", "type": "pad", "params": {"height": 2},
                     "sketch": {"type": "rect", "W": 62, "H": 42}},
                    {"name": "fillet", "type": "fillet", "params": {"radius": 3, "edges": "vertical"}},
                    {"name": "vent_holes", "type": "pattern_linear",
                     "params": {"count": 5, "spacing": 8, "hole_d": 3,
                                "positions": [[-16,0],[-8,0],[0,0],[8,0],[16,0]]}},
                ],
            },
        ],
        "joins": [
            {"part_a": "body", "part_b": "lid", "method": "screw",
             "params": {"screw_size": "M3", "count": 4}},
        ],
    }

    compiler = DesignIntentCompiler()
    tree, report, plan = compiler.compile_and_plan(spec)

    print("=" * 60)
    print(f"Preflight: {'PASS' if report.feasible else 'FAIL'}")
    for issue in report.issues:
        print(f"  [{issue.severity}] {issue.message}")
    print(f"Engine: {plan.engine}")
    print()

    codegen = ParametricCodegen()
    result = codegen.generate(tree, plan, output_dir="./output")

    print("=" * 60)
    print("Generated CadQuery code:")
    print("=" * 60)
    print(result.code)
    print()
    if result.warnings:
        print("Warnings:", result.warnings)


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "demo":
        _demo()
    else:
        print("Usage: python parametric_codegen.py demo")
        _demo()
